config/routes.rb
Rails.application.routes.draw do

  resources :accounts, :books, :courses
  
  resources :users do
    collection do
      patch :set_role
      get :display      
    end
    get :my_profile, on: :member  
  end
  
  controller :admin do
    get    :login,  to: :new
    post   :login,  to: :create
    get    :logout, to: :destroy
    get    :admin, to: :index
    get    :change_password
    patch  :change_password
    get    :search
  end
  
  controller :public do
    get :public, to: :index
    get :about_me
    get :contact_me
    post :contact_me
  end
  

  root "public#index"
  match ':controller(/:action(/:id(.:format)))', via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  has_many :courses, dependent: :destroy
  has_many :accounts, dependent: :destroy
  has_many :books, dependent: :destroy
  
  # for paperclip support
  has_attached_file :image, styles: { small: '150x150'}, default_url: 'images/user.png'
  do_not_validate_attachment_file_type :image
  
  attr_accessor  :password
  
  before_create :before_create
  before_update :before_update
  after_save    :after_save
  before_destroy :prevent_destroy_main_user
  
  validates :first_name, :last_name, :display_name, :username,
            presence: true
  validates :password, :password_confirmation,
            confirmation: true,
            presence: true,
            allow_nil: false,
            allow_blank: false,
            on: :create
  validates :username,
            uniqueness: true  
            
  def name
    [first_name, last_name].join(' ')
  end
  
  def self.make_salt(string)
    Digest::SHA1.hexdigest(string + Time.now.to_s)
  end
  
  def self.hash_with_salt(password, salt)
    return Digest::SHA1.hexdigest("put #{salt} on #{password}")
  end
  
  def authenticated?(password)
    self.hashed_password == User.hash_with_salt(password, self.salt)
  end
  
  def self.authenticate(username,  password)
    user =  self.where(["username = ?", username]).first 
    ( user && user.authenticated?(password) ) ? user : nil
  end
  
  private #------------------------------
    def before_create
      self.salt            = User.make_salt(self.username)
      self.hashed_password  = User.hash_with_salt(@password,  self.salt)
    end
  
    def before_update
      if !@password.nil?
        self.salt            = User.make_salt(self.username) if self.salt.nil?
        self.hashed_password  = User.hash_with_salt(@password,  self.salt)
      end
    end
    
    def after_save
      @password = nil
    end
    
    def prevent_destroy_main_user
      if self.id == 1
        #errors[:base] << "this is the main administrator, You can't delete the main Adminstrator"
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  before_action :set_user, only: [:show, :destroy, :my_profile, :edit, :update]
  
  def index
    @users = User.all    
  end
  
  def display
    display = params[:display] || 'all'
    
    case display
      when 'all'
        @users = User.all
      when 'admin'
        @users = User.where(role_id: 1)
      when 'user'
        @users = User.where(role_id: 2)        
    end
    
  end
  
  
 
  def show    
  end
  
  def set_role
    role_to_set = params[:commit]
    role_id = role_to_set == 'Admin' ? 1 : 2
    
    user_ids_checked = params[:user_ids_checked] || []
    if user_ids_checked.empty?
        @users = User.all
        flash[:notice] = "Select Users to update thier roles First"
        render 'index'
        #redirect_to users_path, notice: "Select Users to update thier roles First"
    else
      user_ids_checked.each do |user_id|
        User.update(user_id, {role_id: role_id})
      end    
      redirect_to users_path, notice: 'Users roles has been updated successfuly'
    end      
  end

 
  def new
    @user = User.new
    render layout: 'public'
  end
    
  def my_profile
    #code
  end
  
  def create        
    @user = User.new(params_user)
    @user.role_id = 2
    if @user.save
        respond_to do |format|
          session[:user_id] = @user.id
          format.html{ redirect_to accounts_path, notice: 'User was created successfully.' }
        end
    else
      render 'new', layout: 'public'
    end    
  end
  
  
  
  def edit
  end
  
  def update          
    if @user.update(params_user)
        respond_to do |format|
          format.html{ redirect_to my_profile_user_path, notice: 'Your Profile has been updated successfully.' }
        end
    else
      render 'edit'
    end    
  end
  
  def destroy
    User.destroy(params[:id])
    
    respond_to do |f|
      f.js{@users = User.order("updated_at DESC")}
      f.html{redirect_to users_path, notice: 'User was successfully destroyed.'}
    end       
  end
  
  private#------------------------------------------------------------
  def set_user
    @user = User.find(params[:id])
  end
  
  def params_user
    params.require(:user).permit(:first_name, :last_name, :display_name, :image, :username, :email, :password, :password_confirmation, :description, :birthdate)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= error_message_for @user if @user.errors.any? %>

<%= form_for @user, html: {multipart: true} do |f| %>
  <div class='col-lg-2 col-md-2 '>    
    <%= image_tag @user.image? ? @user.image.url : 'user.png' , size: '150x150', alt: 'Image Not found' %><br /><br />    
    <%= f.file_field :image %>
    <%= link_to 'Browse..', '#', id: 'users_image', class: 'btn btn-default btn-block' %>
  </div>
  
  <div class='col col-lg-8 col-md-8 '>    
    <div id='user-details'>              
      <table class='table-condensed' id='tbl-new-user'>    
    <tr>
      <td><%= f.label :first_name %></td>
      <td><%= f.text_field :first_name, size: 50, class: 'form-control' %></td>
    </tr>
    <tr>
      <td><%= f.label :last_name %></td>
      <td><%= f.text_field :last_name, size: 50, class: 'form-control' %></td>
    </tr>
    <tr>
      <td><%= f.label :display_name %></td>
      <td><%= f.text_field :display_name, size: 50, class: 'form-control' %></td>
    </tr>
    <tr>
      <td><%= f.label :birthdate %></td>
      <td><%= f.date_select :birthdate, {size: 50}, class: 'form-control' %></td>
    </tr>
    <tr>
      <td><%= f.label :username %></td>
      <td><%= f.text_field :username, size: 50, class: 'form-control' %></td>
    </tr>
    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.email_field :email, size: 50, class: 'form-control' %></td>
    </tr>
    <% if action_name == 'new' %>
      <tr>
      <td><%= f.label :password %></td>
      <td>
        <%= f.password_field :password, size: 50, class: 'form-control' %>        
      </td>
    </tr>
    <tr>
      <td><%= f.label :password_confirmation %></td>
      <td>
        <%= f.password_field :password_confirmation, size: 50, class: 'form-control' %>        
      </td>
    </tr>
    <% end %>    
    <tr>
      <td><%= f.label :description %></td>
      <td><%= f.text_area :description, size: '50x2', class: 'form-control' %></td>
    </tr>    
  </table> 
    </div>
  </div>
   
  <div id='frm-user-submit'><%= f.submit( (@user.new_record? ? "Create New User" : "Save Changes"),  class: 'btn btn-success') %></div>

<% end -%>

app/views/users/_user.html.erb
<table class= 'table table-condensed user-show-tbl'>
  <% if admin? %>
    <tr>
      <th>User Role</th>
      <td><%= user.role.name %></td></td>
    </tr>
  <% end %>
  <tr>
    <th>Username</th>
    <td><%= user.username %></td></td>
  </tr>
  <tr>
    <th>Name</th>
    <td><%= user.name%></td>
  </tr>
  <tr>
    <th>Display Name</th>
    <td><%= user.display_name %></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= user.email %></td>
  </tr>
  <tr>
    <th>Birthdate</th>
    <td><%= user.birthdate if user.birthdate %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= user.description%></td>
  </tr>
  <tr>
    <th>Created at</th>
    <td><%= user.created_at.strftime("%B %d %Y") %></td>
  </tr>
</table>

app/views/users/_users.html.erb
<!-- needs @users -->
<table class='table table-condensed table-responsive'>
    <tr>
      <th></th>
      <th>User Role</th>
      <th>Username</th>
      <th>Name</th>
      <th>Display Name</th>
      <th>Birthdate</th>
      <th>Description</th>
      <th>Image</th>      
      <th>Created at</th>
    </tr>
  <% @users.each do |user| %>  
    <tr>
      <td><%= check_box_tag "user_ids_checked[]", user.id %></td>      
      <td><%= user.role.name if user.role %></td>      
      <td><%= user.username %></td>
      <td><%= user.name %></td>
      <td><%= user.display_name %></td>
      <td><%= user.birthdate.strftime("%d %B %Y") if user.birthdate %></td>
      <td><%= user.description %></td>
      <td><%= user.image %></td>
      <td><%= user.created_at.strftime("%d %B %Y") %></td>      
      <td>
        <div id='actions'>
            <%= link_to "Preview", user_path(user), class: 'btn btn-info btn-xs', data: {toggle: 'modal', target: '.bs-example-modal-lg',remote: true} %>            
            <%= link_to "Destroy", user_path(user), class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: "Are you sure ?", remote: true} %>
        </div>        
      </td>
    </tr>    
  <% end %>
</table>

app/views/users/destroy.js.erb
<% if @users.any? %>
    $('#users').html("<%= j render partial: 'users' %>");
<% else %>
    $('#users').html("No users available.");  
<% end %>

$("#notice").html("<h3>User was successfully destroyed.</h3>").slideDown().delay(3500).slideUp();

app/views/users/display.js.erb
//for display select change processing
<% if @users.any? %>
    $("#users").html("<%= j render partial: 'users' %>"); 
<% else %>
    $("#users").html("<h3>No Users Match Your Selecting.</h3>"); 
<% end %>

app/views/users/edit.html.erb
<h2>My Profile</h2>
<br/><br/>

<%= render 'form' %>  

app/views/users/index.html.erb
<h1>Current Users</h1>

<div>
    <b>Display </b>
    <%= radio_button_tag :display, 'all', checked: true %> All
    <%= radio_button_tag :display, 'admin'              %> Admin
    <%= radio_button_tag :display, 'user'               %> User
</div><br />

<%= form_tag(set_role_users_path) do %>
  
  <div id='users'>
    <%= @users.any? ? render(partial: 'users') : "No Users Available." %>  
  </div>
  
  <br/><br/>
  
  <div>
    <b>Mark Selected Users As</b> <%= submit_tag "User", class: 'btn btn-primary' %>
    <%= submit_tag "Admin", class: 'btn btn-success' %>
  </div>
<% end -%>

app/views/users/my_profile.html.erb
<div clss='row'>
  <h2>My Profile </h2>
  <div class='col-lg-2 col-md-2'>
    
    <%= image_tag '',size: '150x150', alt: 'Image Not found' %><br /><br />    
    <%= link_to "Change Image", "", class: 'btn btn-primary' %>
  </div>
  
  <div class='col-lg-2 col-md-3'></div>
  
  <div class='col-lg-8 col-md-7'>    
    <div id='user-details'>              
      <%= render @user %>
      <hr>
      <span id='statistcs'>
        <%= pluralize current_user.courses.count, 'Course' %> - 
        <%= pluralize current_user.books.count, 'Book' %> - 
        <%= pluralize current_user.accounts.count, 'Account' %>
      </span>
      <div id='edit-profile-link'>
        <%= link_to "Edit My Profile", edit_user_path(current_user.id), "data-no-turbolink" => "true", class: 'btn btn-success' %>
      </div>
    </div>
  </div>
    
</div>
  

app/views/users/new.html.erb
<h2>Create New User</h2>
<br/><br/>

<%= render 'form' %> 

app/views/users/show.html.erb
<%= render @user %>

app/views/users/show.js.erb
$('.modal-title').html("Display User");
$("#status").html("");
$(".modal-body").html("<%= j render @user %>");