config/routes.rb
Rails.application.routes.draw do

  resources :accounts, :books, :courses
  
  resources :users do
    collection do
      patch :set_role
      get :display      
    end
    get :my_profile, on: :member  
  end
  
  controller :admin do
    get    :login,  to: :new
    post   :login,  to: :create
    get    :logout, to: :destroy
    get    :admin, to: :index
    get    :change_password
    patch  :change_password
    get    :search
  end
  
  controller :public do
    get :public, to: :index
    get :about_me
    get :contact_me
    post :contact_me
  end
  

  root "public#index"
  match ':controller(/:action(/:id(.:format)))', via: [:get, :post]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?, :admin?
  
  def current_user
    @current_user ||= User.includes([{accounts: :type}, :role, {courses: :category}]).find_by_id(session[:user_id])
  end
  
  def logged_in?
    current_user != nil
  end
  
  def admin?
    current_user.role && current_user.role.name == 'admin' 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_message_for object
    render partial: 'application/error_messages', locals: {object: object}
  end
  
  #def flash_with_toastr
  #  javascript_tag do
  #    toastr.error('message', 'error')      
  #  end
  #end  
    #flash[:error] = 'error'
    #flash.each do |type, msg|
    #  if ['success', 'warning', 'error', 'info'].include? type
    #    javascript_tag do
    #      toastr.error('message', 'error');
    #      #toastr.key(msg, key);
    #    end
    #  else
    #    
    #  end
    #end
  
end

app/views/application/_error_messages.html.erb
<p>there were <%= pluralize object.errors.size, "error" %> prohipeted this record from been saved the problem were in the following records</p>
<ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

app/views/application/_modal.html.erb
<div class="modal fade bs-example-modal-lg" role="dialog" aria-labelledby="gridSystemModalLabel">
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h3 class="modal-title" id="gridSystemModalLabel"></h3>
    </div>
    <div id='status'></div>          
    <div class="modal-body">        
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>        
    </div>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/application/_sidebar.html.erb
<div id='accor-container'>
  <h2>Manage Accounts</h2>
  <div><%= content_for :user_accounts %></div>
  
  <h2>Manage Courses</h2>
  <div><%= yield :user_courses %></div>
  
  <h2>Manage Books</h2>
  <div><%= yield :user_books %></div>
  
  <% if admin? %>
    <h2>Manage Users</h2>
    <div><%= link_to('Manage Users'   , users_path)  %></div>
  <% end %>
</div>

app/views/application/_user_accounts_books_courses_details.html.erb
<!-- Set User Courses categories displayed in nav bar-->
<% content_for :user_courses do %>  
  <% course_categories = current_user.courses.limit(5).map{ |course| course.category if course.category }.uniq.compact %>
  
  <li><%= link_to 'All Course', courses_path(display: 'all') %></li>
  <% course_categories.each do |cat| %>
    <li><%= link_to cat.name, courses_path(display: cat.id) %></li>  
  <% end %>
    
<% end %>

<!-- Set User Accounts Types displayed in nav bar-->
<% content_for :user_accounts do %>  
  <% account_types = current_user.accounts.limit(5).map{ |acc| acc.type if acc.type }.uniq.compact %>
  
  <li><%= link_to 'All Accounts', accounts_path(display: 'all')  %></li>
  <% account_types.each do |type| %>
    <li><%= link_to type.name, accounts_path(display: type.id)  %></li>  
  <% end %>
    
<% end %>

<!-- Set User Books categories displayed in nav bar-->
<% content_for :user_books do %>  
  <% course_categories = current_user.books.limit(5).map{ |course| course.category if course.category }.uniq.compact %>
  
  <li><%= link_to 'All Books', books_path(display: 'all')  %></li>
  <% course_categories.each do |cat| %>
    <li><%= link_to cat.name, books_path(display: cat.id)  %></li>  
  <% end %>
    
<% end %>