config/routes.rb
Rails.application.routes.draw do

  resources :accounts, :books, :courses
  
  resources :users do
    collection do
      patch :set_role
      get :display      
    end
    get :my_profile, on: :member  
  end
  
  controller :admin do
    get    :login,  to: :new
    post   :login,  to: :create
    get    :logout, to: :destroy
    get    :admin, to: :index
    get    :change_password
    patch  :change_password
    get    :search
  end
  
  controller :public do
    get :public, to: :index
    get :about_me
    get :contact_me
    post :contact_me
  end
  

  root "public#index"
  match ':controller(/:action(/:id(.:format)))', via: [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_titel || "My Site" %></title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>    
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>      
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>">
  <%= render partial: 'application/user_accounts_books_courses_details' %>   
  <%= render partial: 'application/modal' %>
  
 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= content_tag('b', link_to( "MY SITE",  contact_me_path, class: "navbar-brand") ) %>      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag( search_path(search_text: params[:search_text]), method: 'get', class: "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field_tag :search_text, params[:search_text],  size: 40, class: "form-control", placeholder: "Search" %>
        </div>
        <%= button_tag(type: "submit", class: "btn btn-default btn-search") do %>
          <span class="glyphicon glyphicon-search btn-search"></span> Search
        <% end %>
      <% end %>
      
      <ul class="nav navbar-nav navbar-right">
        <li class='dropdown'>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.display_name  %><%= image_tag 'user.png', size: '30x30', id:'nav-user-img' %><!--<span class="glyphicon glyphicon-cog "></span>--></a>              
          <ul class="dropdown-menu">
            <li><%= link_to "MY PROFILE", my_profile_user_path(current_user.id)  %></li>            
            <li><%= link_to "Settings", '#' %></li>
            <li><%= link_to "Change password", change_password_path  %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "LOGOUT", logout_path %></li>
          </ul>
        </li>
      </ul>
              
      <ul class="nav navbar-nav navbar-left" id='left-nav'>
        <li><%= link_to "HOME PAGE", public_path %></li> 
        <li class = "dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Courses <span class="glyphicon glyphicon-triangle-bottom"></span></a>
          <ul class="dropdown-menu">            
            <%= yield :user_courses %>
          </ul>
        </li>
        <li class = "dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ACCOUNTS <span class="glyphicon glyphicon-triangle-bottom"></span></a>
          <ul class="dropdown-menu">
            <%= yield :user_accounts %>            
          </ul>
        </li>
        <li class = "dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">BOOKS <span class="glyphicon glyphicon-triangle-bottom"></span></a>
          <ul class="dropdown-menu">
            <%= yield :user_books %>
          </ul>
        </li>                        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
 
 <div class="main-container">
    <div id='notice'></div>
    <!--<% if flash[:notice] %>        
        <%= javascript_tag do %>
          $("#notice").html("<h3><%= flash[:notice] %></h3>").slideDown().delay(3500).slideUp();
        <% end %>      
    <% end %>-->
    
    <% unless flash.empty? %>
      <% flash.each do |type, msg| %>
        <% if ['success', 'warning', 'error', 'info'].include? type.to_s %>          
          <%= javascript_tag "toastr.#{type}('#{msg}');" %>
        <% else %>
          <%= javascript_tag "toastr.info('#{msg}');" %>  
        <% end %>                
      <% end %>
    <% end %>
    
    <div id='main-row' class='row'>
      <div class='col-lg-2'>
        <%= render(partial: 'application/sidebar')  %>
      </div>
      
      <div class='col-lg-10'>
        <%= yield %>
      </div>      
    </div>
    
 </div>
 
 <div id='footer'> copyright 23/11/2015 </div>   
  
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_titel || "My Site" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>">
 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= content_tag('b', link_to( "My Site", contact_me_path, class: "navbar-brand") ) %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
      <ul class="nav navbar-nav navbar-right">
            <li><%= link_to("CONTROL PANEL", admin_path) if logged_in? %></li> 
            <li><%= link_to "LOGIN", login_path %></li>       
            <li><%= link_to "SIN UP", new_user_path %></li>                  
            <li><%= link_to "ABOUT ME", about_me_path %></li>            
            <li><%= link_to "CONTACT ME", contact_me_path %></li>                                
      </ul>      
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
 
 <div class="main-container container">
    <div id='notice'></div>
   <!-- <% if flash[:notice] %>        
        <%= javascript_tag do %>
          $("#notice").html("<h3><%= flash[:notice] %></h3>").slideDown().delay(3500).slideUp();
        <% end %>      
    <% end %>
    -->
    <% unless flash.empty? %>
      <% flash.each do |type, msg| %>
        <% if ['success', 'warning', 'error', 'info'].include? type.to_s %>          
          <%= javascript_tag "toastr.#{type}('#{msg}');" %>
        <% else %>
          <%= javascript_tag "toastr.info('#{msg}');" %>  
        <% end %>                
      <% end %>
    <% end %>
    
    <%= yield %>
 </div>
    
 <div id='footer'>
  copyright 23/11/2015
 </div>   
</body>
</html>