config/routes.rb
Rails.application.routes.draw do

  resources :accounts, :books, :courses
  
  resources :users do
    collection do
      patch :set_role
      get :display      
    end
    get :my_profile, on: :member  
  end
  
  controller :admin do
    get    :login,  to: :new
    post   :login,  to: :create
    get    :logout, to: :destroy
    get    :admin, to: :index
    get    :change_password
    patch  :change_password
    get    :search
  end
  
  controller :public do
    get :public, to: :index
    get :about_me
    get :contact_me
    post :contact_me
  end
  

  root "public#index"
  match ':controller(/:action(/:id(.:format)))', via: [:get, :post]

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :type, class_name: 'AccountType', foreign_key: :account_type_id
  belongs_to :user
  
  validates :type, associated: {message: 'exist in the list, you should select instead of adding new one'}
  validates :username, :password,
            presence: true
end

app/models/account_type.rb
class AccountType < ActiveRecord::Base
  has_many :accounts, dependent: :destroy
    
  validates :name,
           uniqueness: {case_sensitive: false}
             
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :set_account_types, only: [:new, :edit, :index, :display]
  
  def index
    #for add new account using ajax 
    @account = Account.new
    
    display = params[:display] || 'all'
                        
    @accounts = (display == 'all') ? Account.where(user_id: session[:user_id]).order("updated_at DESC") :
                Account.where(user_id: session[:user_id], account_type_id: display).order("updated_at DESC")
    respond_to do  |f|
      f.js{}
      f.html{}
    end
  end

  def show
  end

  def new
    @account = Account.new
    respond_to do |f|
      f.html{}
      f.js{}
    end
    
  end
  
  def create
    @account         = Account.new(params_account)
    @account.user_id = current_user.id
    @account.type    = AccountType.new(name: params[:account_type]) if params[:account_type].present?
    
    if @account.save
      flash[:success] = 'The account has been Successfully created'
      redirect_to accounts_path
      #$state = 'create'
    else
      set_account_types
      render 'new'  
    end    
  end

  def edit
    respond_to do |f|
      f.html{}
      f.js{}
    end
  end
  
  def update
    updated_params_account = params_account
    
    if params[:account_type].present?
        @account.type = AccountType.new(name: params[:account_type])
        updated_params_account.delete('account_type_id')
    end
        
    if @account.update(updated_params_account)
      flash[:success] = 'The account has been Successfully updated'
      redirect_to accounts_path
      #$state = 'update'
    else
      set_account_types
      render 'edit'  
    end
  end
   
  def destroy
    Account.destroy(params[:id])
    
    respond_to do |f|
      f.js{@accounts = Account.where(user_id: session[:user_id]).order("updated_at DESC")}
      f.html{redirect_to accounts_path, notice: 'Account was successfully destroyed.'}
    end       
  end
  
  #def display
  #  display = params[:display]        
  #  @accounts = (display == 'all') ? Account.where(user_id: session[:user_id]).order("updated_at DESC") : Account.where(user_id: session[:user_id], account_type_id: display).order("updated_at DESC")
  #  
  #  respond_to do  |f|
  #    f.js
  #  end
  #end
  
  private#-----------------------------------------------------------
  def set_account
    @account = Account.find(params[:id])
  end
  
  def set_account_types
    @account_types = AccountType.all.map{|acc_type| [acc_type.name, acc_type.id]}.uniq
    @user_account_types = current_user.accounts.map{ |acc| [acc.type.name , acc.type.id] if acc.type}.compact.uniq
  end
  
  def params_account
    params.require(:account).permit(:username, :email, :password, :account_type_id, :other_emails, :reason_create, :notes, :created_at, :type)
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<table class= 'table table-bordered table-condensed account-show-tbl'>
  <tr>
    <th>Account Type</th>
    <td><%= account.type ? account.type.name : "None" %></td></td>
  </tr>
  <tr>
    <th>Username</th>
    <td><%= account.username %></td></td>
  </tr>
  <tr>
    <th>Email</th>
    <td><%= account.email %></td>
  </tr>
  <tr>
    <th>Password</th>
    <td><%= account.password %></td>
  </tr>
  <tr>
    <th>Other Emails</th>
    <td><%= account.other_emails %></td>
  </tr>
  <tr>
    <th>Reason creating </th>
    <td><%= account.reason_create %></td>
  </tr>
  <tr>
    <th>Created at</th>
    <td><%= account.created_at.strftime("%B %d %Y") %></td>
  </tr>
  <tr>
    <th>Notes</th>
    <td><%= account.notes %></td>
  </tr>
</table>

app/views/accounts/_accounts.html.erb
<table class='table  table-condensed table-responsive'>
    <tr>
      <th>Account type</th>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>Other Emails</th>
      <th>Reason create account</th>
      <th>Created at</th>
      <th>Notes</th>
    </tr>
  <% @accounts.each do |acc| %>  
    <tr>
      <td>
        <%= acc.type.name if acc.type %>
        <%= "none" if acc.account_type_id == 0 || acc.account_type_id == nil %>        
      </td>      
      <td><%= acc.username %></td>
      <td><%= acc.email %></td>
      <td><%= acc.password %></td>
      <td><%= acc.other_emails %></td>
      <td><%= acc.reason_create %></td>
      <td><%= acc.created_at.strftime("%B %d %Y") %></td>
      <td><div id='notes'><%= acc.notes %></div></td>
      <td>
        <div id='actions'>
            <%= link_to("Show", account_path(acc), class: 'btn btn-info btn-xs', data: {toggle: 'modal', target: '.bs-example-modal-lg', remote: true}) if controller_name != 'Admin' && action_name != 'search' %>
            <%= link_to "Edit", edit_account_path(acc), class: 'btn btn-success btn-xs', data: {toggle: 'modal', target: '.bs-example-modal-lg',remote: true} if controller_name != 'Admin' && action_name != 'search' %>
            <%= link_to "Destroy", account_path(acc), class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: "Are you sure ?", remote: true} if controller_name != 'Admin' && action_name != 'search' %>
        </div>        
      </td>
    </tr>    
  <% end %>
</table>

app/views/accounts/_form.html.erb
<%= error_message_for @account if @account.errors.any? %>

<%= form_for @account, remote: true do |f| %>
  <table class='table-condensed'>
    <tr>
      <th><%= f.label :username %></th>
      <td> <%= f.text_field :username, size: 50, class: 'form-control' %></td>
    </tr>
    <tr>
      <th><%= f.label :email %></th>
      <td><%= f.email_field :email, size: 50, class: 'form-control' %></td>
    </tr>
    <tr>
      <th><%= f.label :password %></th>
      <td><%= f.password_field :password, size: 50, class: 'form-control' %></td>
    </tr>
    <tr>
      <th><%= f.label :account_type_id, "Account Type" %></th>
      <td>
        <%= f.select(:account_type_id, [["none", 0]] + @account_types , {}, {class: "form-control"}) %> 
        New <%= text_field_tag(:account_type, nil, size: 30, class: 'form-control') %>
      </td>
    </tr>    
      
    <tr>
      <th><%= f.label :other_emails%></th>
      <td><%= f.text_area :other_emails, size: '47x3', class: 'form-control' %></td>
    </tr>
    <tr>
      <th><%= f.label :reason_create, "Reason create this account" %></th>
      <td><%= f.text_field :reason_create, size: 50, class: 'form-control' %></td>
    </tr>
    <tr>
      <th><%= f.label :created_at %></th>
      <td><%= f.date_select :created_at, {}, {class: 'form-control'} %></td>
    </tr>
    <tr>
      <th><%= f.label :notes %></th>
      <td> <%= f.text_area :notes, size: '47x3', class: 'form-control' %></td>
    </tr>    
  </table>
  <div id='form-submit'><%= f.submit(@account.id ? "Update Account" : "Create Account", {class: 'btn btn-primary'}) %></div>
<% end %>

app/views/accounts/destroy.js.erb
<% if @accounts.any? %>
    $('#accounts').html("<%= j render partial: 'accounts' %>");
<% else %>
    $('#accounts').html("No accounts available.");  
<% end %>

$("#notice").html("<h3>Account was successfully destroyed.</h3>").slideDown().delay(3500).slideUp();

app/views/accounts/edit.html.erb
<h1>Edit Account</h1>
<%= render partial: 'form' %>

app/views/accounts/edit.js.erb
$('.modal-title').html("Update Account");
$('.modal-body').html("<%= j render partial: 'form' %>");
$("#status").html("");

app/views/accounts/index.html.erb
<h1>My Accounts</h1>

<div><b>Display </b> <%= select_tag(:display, options_for_select([['All', 'all']] + @user_account_types), class: "form-control display-select") %></div> <br />  

<div id='result-display'>
  <div id='accounts'><%= @accounts.any? ? render(partial: 'accounts') : "No Accounts Available." %></div>  
</div>
<br/><br/>

<div><%= link_to "Create New Account", new_account_path, data: {toggle: 'modal', target: '.bs-example-modal-lg', remote: true}, class: 'btn btn-primary' %></div>

app/views/accounts/index.js.erb
// display accounts
<% if @accounts.any? %>
    $("#accounts").html("<%= j render partial: 'accounts' %>"); 
<% else %>
    $("#accounts").html("<h3>No Accounts Match Your Selecting.</h3>"); 
<% end %>

toastr.success('<%= flash[:success] %>') ;
$('.modal').modal('hide');

app/views/accounts/new.html.erb
<h1>New Account</h1>
<%= render partial: 'form' %>

app/views/accounts/new.js.erb
$('.modal-title').html("Create Account");
$('.modal-body').html("<%= j render partial: 'form' %>");
$("#status").html("");

app/views/accounts/show.html.erb
<%= link_to "Edit", edit_account_path(@account), class: 'btn btn-success btn-xs' %>
<%= link_to "Destroy", account_path(@account), class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: "Are you sure ?"} %>
<br /><br />
<%= render @account %>

app/views/accounts/show.js.erb
$('.modal-title').html("Display Account");
$("#status").html("");
$(".modal-body").html("<%= j render @account %>");